services:
  app:
    image: ghcr.io/syauqi-n/soqipdf:1.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - tmp_data:/app/tmp
    restart: unless-stopped

volumes:
  tmp_data:
